//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_JobSeeker
    {
        public decimal ID { get; set; }
        public Nullable<decimal> JobId { get; set; }
        public Nullable<decimal> SeekerId { get; set; }
    
        public virtual Seeker Seeker { get; set; }
    }
}
