//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.JobOes = new HashSet<JobO>();
        }
    
        public decimal CompId { get; set; }
        public string CompName { get; set; }
        public Nullable<decimal> CompLocationId { get; set; }
        public Nullable<System.DateTime> CompEstDate { get; set; }
        public Nullable<decimal> CompUserId { get; set; }
        public string CompPhoto { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobO> JobOes { get; set; }
    }
}
