//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public decimal EduId { get; set; }
        public string EduLevel { get; set; }
        public string SchoolName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Branch { get; set; }
        public Nullable<decimal> CvId { get; set; }
        public Nullable<decimal> UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual CV CV { get; set; }
    }
}
