//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAREEREntities : DbContext
    {
        public CAREEREntities()
            : base("name=CAREEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_JobSeeker> C_JobSeeker { get; set; }
        public virtual DbSet<CV> CVs { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Experience> Experiences { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<JobO> JobOes { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Seeker> Seekers { get; set; }
    }
}
