//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobO
    {
        public decimal JobId { get; set; }
        public string JobTitle { get; set; }
        public string JobPosition { get; set; }
        public string JobDetail { get; set; }
        public Nullable<decimal> JobLocationId { get; set; }
        public Nullable<decimal> JobCompId { get; set; }
        public string JobPhoto { get; set; }
        public Nullable<decimal> UserId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual User User { get; set; }
        public virtual Company Company { get; set; }
    }
}
