//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seeker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seeker()
        {
            this.C_JobSeeker = new HashSet<C_JobSeeker>();
            this.CVs = new HashSet<CV>();
        }
    
        public decimal empId { get; set; }
        public Nullable<decimal> empUserId { get; set; }
        public string empName { get; set; }
        public string empSurname { get; set; }
        public string empEmail { get; set; }
        public string empPhone { get; set; }
        public string empAddress { get; set; }
        public Nullable<decimal> empCvId { get; set; }
        public string empMainJob { get; set; }
        public Nullable<decimal> empMainLocation { get; set; }
        public string empPhoto { get; set; }
        public Nullable<System.DateTime> empBirthDate { get; set; }
        public string empDetail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_JobSeeker> C_JobSeeker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CV> CVs { get; set; }
        public virtual Location Location { get; set; }
        public virtual User User { get; set; }
    }
}
